name: Deploy z-player to EC2 Root

on:
  push:
    branches:
      - tests/updates

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          # Игнорируем проверку хоста, чтобы не возиться с keyscan
          echo "Host *" > ~/.ssh/config
          echo "    StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Deployment
        run: |
          ssh -i ~/.ssh/id_rsa root@${{ secrets.SSH_HOST }} << 'EOF'
            set -e
            echo "🔥 Внутри! Если упадет — значит ты не сделал restart ssh на сервере."
            
            PROJECT_DIR="/root/z-player"
            mkdir -p "$PROJECT_DIR"
            cd "$PROJECT_DIR"

            # Чистый деплой
            if [ ! -d ".git" ]; then
              git clone -b tests/updates https://github.com/${{ github.repository }}.git .
            else
              git fetch origin tests/updates
              git reset --hard FETCH_HEAD
            fi

            # Пересборка
            docker stop z-player || true
            docker rm z-player || true
            docker build -t z-player .
            docker run -d --restart unless-stopped --name z-player -p 3001:3001 z-player
            
            echo "🚀 Всё взлетело, можешь отдыхать."
          EOF
